/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 15 10:39:30 GMT 2018
 */

package com.ckjava.xutils.db;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.ckjava.xutils.db.ObjectListHandler;
import java.sql.ResultSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ObjectListHandler_ESTest extends ObjectListHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ObjectListHandler objectListHandler0 = new ObjectListHandler();
      // Undeclared exception!
      try { 
        objectListHandler0.handle((ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.ckjava.xutils.db.ObjectListHandler", e);
      }
  }
}
