/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Dec 15 10:39:30 GMT 2018
 */

package com.ckjava.xutils.db;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class ObjectListHandler_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.ckjava.xutils.db.ObjectListHandler"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "GBK"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\ck\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "CN"); 
    java.lang.System.setProperty("user.dir", "D:\\workspace\\git-workspace\\play\\xutils"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\ck"); 
    java.lang.System.setProperty("user.language", "zh"); 
    java.lang.System.setProperty("user.name", "ck"); 
    java.lang.System.setProperty("user.timezone", "Asia/Shanghai"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ObjectListHandler_ESTest_scaffolding.class.getClassLoader() ,
      "com.ckjava.xutils.db.ObjectListHandler",
      "org.apache.commons.dbutils.ResultSetHandler"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ObjectListHandler_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.ckjava.xutils.db.ObjectListHandler",
      "org.sqlite.SQLiteConfig$TransactionMode",
      "org.sqlite.SQLiteConfig",
      "org.sqlite.SQLiteConfig$Encoding",
      "org.sqlite.SQLiteConfig$JournalMode",
      "org.sqlite.SQLiteConfig$LockingMode",
      "org.sqlite.SQLiteConfig$SynchronousMode",
      "org.sqlite.SQLiteConfig$TempStore",
      "org.sqlite.SQLiteConfig$DatePrecision",
      "org.sqlite.SQLiteConfig$DateClass",
      "org.sqlite.SQLiteConfig$HexKeyMode",
      "org.sqlite.SQLiteConfig$Pragma",
      "org.sqlite.core.CoreConnection",
      "org.sqlite.jdbc3.JDBC3Connection",
      "org.sqlite.jdbc4.JDBC4Connection",
      "org.sqlite.SQLiteConnection",
      "org.sqlite.SQLiteOpenMode",
      "org.sqlite.date.FormatCache",
      "org.sqlite.date.FastDateFormat$1",
      "org.sqlite.date.FastDateFormat",
      "org.sqlite.date.FormatCache$MultipartKey",
      "org.sqlite.date.FastDatePrinter",
      "org.sqlite.date.FastDatePrinter$PaddedNumberField",
      "org.sqlite.date.FastDatePrinter$CharacterLiteral",
      "org.sqlite.date.FastDatePrinter$TwoDigitMonthField",
      "org.sqlite.date.FastDatePrinter$TwoDigitNumberField",
      "org.sqlite.date.FastDateParser$Strategy",
      "org.sqlite.date.FastDateParser$NumberStrategy",
      "org.sqlite.date.FastDateParser$1",
      "org.sqlite.date.FastDateParser$2",
      "org.sqlite.date.FastDateParser$3",
      "org.sqlite.date.FastDateParser$4",
      "org.sqlite.date.FastDateParser$ISO8601TimeZoneStrategy",
      "org.sqlite.date.FastDateParser",
      "org.sqlite.date.FastDateParser$CopyQuotedStrategy",
      "org.sqlite.core.DB",
      "org.sqlite.core.NativeDB",
      "org.sqlite.SQLiteJDBCLoader",
      "org.sqlite.SQLiteJDBCLoader$1",
      "org.sqlite.util.OSInfo",
      "org.hsqldb.jdbc.JDBCDriver",
      "org.sqlite.JDBC",
      "org.sqlite.core.CoreStatement",
      "org.sqlite.jdbc3.JDBC3Statement",
      "org.sqlite.jdbc4.JDBC4Statement",
      "org.sqlite.core.CorePreparedStatement",
      "org.sqlite.jdbc3.JDBC3PreparedStatement",
      "org.sqlite.jdbc4.JDBC4PreparedStatement",
      "org.sqlite.core.CoreResultSet",
      "org.sqlite.jdbc3.JDBC3ResultSet",
      "org.sqlite.jdbc4.JDBC4ResultSet",
      "org.springframework.jndi.JndiTemplate",
      "org.apache.commons.logging.impl.Jdk14Logger",
      "org.springframework.jndi.JndiTemplate$1"
    );
  }
}
