/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 15 10:38:33 GMT 2018
 */

package com.ckjava.xutils.db;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.ckjava.xutils.db.ObjectListWithColumnHandler;
import java.sql.ResultSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ObjectListWithColumnHandler_ESTest extends ObjectListWithColumnHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ObjectListWithColumnHandler objectListWithColumnHandler0 = new ObjectListWithColumnHandler();
      // Undeclared exception!
      try { 
        objectListWithColumnHandler0.handle((ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.ckjava.xutils.db.ObjectListWithColumnHandler", e);
      }
  }
}
