/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 15 10:38:43 GMT 2018
 */

package com.ckjava.xutils;

import org.junit.Test;
import static org.junit.Assert.*;
import com.ckjava.xutils.OSUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OSUtils_ESTest extends OSUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = OSUtils.getCurrentOSType();
      assertEquals("windows", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      OSUtils oSUtils0 = new OSUtils();
  }
}
